name: Build, Validate and Deploy SAM App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-validate-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # Or fallback to 3.11 if 3.13 isn't on GitHub runners yet

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Your region

      - name: Build SAM Application
        run: sam build

      - name: Validate SAM Template
        run: sam validate

      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name log-service --capabilities CAPABILITY_IAM --region us-east-1

